# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help


name: R-CMD-check

on:
  push:
    branches:
      - 'suite'
      - 'suite_dev'
  # pull_request:
  #   branches:
  #     - 'suite'
  #     - 'suite_dev'

permissions:
  contents: read

jobs:
  R-CMD-check:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config: # matrix of system runners to run workflow on
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          # - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    steps:

      - name: Remove vignettes dir
        run: rm -rf 'vignettes/'
        shell: bash

      - name: Checkout repo for workflow access
        uses: actions/checkout@v3

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Set up dependencies (general)
        uses: r-lib/actions/setup-r-dependencies@v2
        env:
          _R_CHECK_FORCE_SUGGESTS: false
          _R_CHECK_RD_XREFS: false
        with:
          dependencies: '"hard"' # do not use suggested dependencies
          extra-packages: any::rcmdcheck, any::testthat, any::rlang, any::R.utils, any::remotes, any::covr, any::spdep, any::future.apply, github::drieslab/GiottoData

      - name: Test python env install
        run: |
          if (!GiottoClass::checkGiottoEnvironment()) {
            GiottoClass::installGiottoEnvironment()
          }
        shell: Rscript {0}

      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"' # workflow errors on error only, can change to include warnings

      # show testthat output for ease of access
      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
